{"name": "Test to verify that user can complete the task with exception", "status": "passed", "description": "This test case tests completing the task with exception", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733760208791, "stop": 1733760220272, "uuid": "ded1858a-4372-4b73-845e-3ba2d676682e", "historyId": "5f8625f551487b3af2c2c04a2cc3bc19", "testCaseId": "18be0cdf41984c208eb7812a8b1c6e1b", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_task_with_exception", "labels": [{"name": "tag", "value": "complete_task_with_exception"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86ctxmvta", "name": "https://app.clickup.com/t/86ctxmvta"}]}