{"name": "Test to verify that user can complete the job by approving the criteria type validation exception", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_number_parameter_exception_management_execution.TestNumberParameterExceptionManagementExecution object at 0x7af8221a5e50>\nuser_group_creation = 'Auto_Test_user_group_TestNumberParameterExceptionManagementExecution_760', job_execution_by = 'user_group', users_list = []\n\n    @allure.title(\"Test to verify that user can complete the job by approving the criteria type validation exception\")\n    @allure.description(\n        \"This test case validates that user of usergroup can complete the job by approving the exception for criteria \"\n        \"type validation with parameterized value\")\n    @allure.link(\"https://app.clickup.com/t/86cvh7x4c\")\n    @pytest.mark.scenario\n    @pytest.mark.job\n    @pytest.mark.exception_management_workflow\n    @pytest.mark.validate_job_completion_by_user_group_on_criteria_type_validation_with_parameterized_value\n    @pytest.mark.parametrize(\"job_execution_by, users_list\", [(\"user_group\", [])])\n    def test_validate_job_completion_by_user_group_on_criteria_type_validation_with_parameterized_value(self,\n                                                                                                        user_group_creation,\n                                                                                                        job_execution_by,\n                                                                                                        users_list):\n>       process_data = self.process_obj.test_add_number_parameter_with_criteria_type_validation_enabled_approval_flow_condition_and_parameterized_value()\n\ntests/scenarios/job/test_number_parameter_exception_management_execution.py:243: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/scenarios/test_number_parameter_exception_management.py:385: in test_add_number_parameter_with_criteria_type_validation_enabled_approval_flow_condition_and_parameterized_value\n    validate_checklist()\ntests/unit/prototyping/process.py:186: in validate_checklist\n    status_200(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = ''\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case validates that user of usergroup can complete the job by approving the exception for criteria type validation with parameterized value", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733499673319, "stop": 1733499674640, "uuid": "74b45519-d003-40e0-8aa6-f9594b1d1410", "historyId": "053e1679098d902ea682440024fb43a1", "testCaseId": "f599e8e0b6cab7157a16ac8c8cbbefb1", "fullName": "tests.scenarios.job.test_number_parameter_exception_management_execution.TestNumberParameterExceptionManagementExecution#test_validate_job_completion_by_user_group_on_criteria_type_validation_with_parameterized_value", "labels": [{"name": "tag", "value": "validate_job_completion_by_user_group_on_criteria_type_validation_with_parameterized_value"}, {"name": "tag", "value": "exception_management_workflow"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_number_parameter_exception_management_execution"}, {"name": "subSuite", "value": "TestNumberParameterExceptionManagementExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_number_parameter_exception_management_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvh7x4c", "name": "https://app.clickup.com/t/86cvh7x4c"}]}