{"name": "Test to validate error when user tries to complete the task with executing some of the parameters", "status": "passed", "description": "This test case tests validating error when user tries to complete task after executing some of the parameters", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733498545190, "stop": 1733498567650, "uuid": "b5712045-1765-471f-b039-e19362ab9e74", "historyId": "872d2e9ae24a3d247fad877a9c754cef", "testCaseId": "1c767ceb1ff0f839d3f8d55eec3bf9b4", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_validate_error_on_completing_task_after_executing_parameters", "labels": [{"name": "tag", "value": "validate_error_on_completing_task_after_executing_parameters"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cu3nx81", "name": "https://app.clickup.com/t/86cu3nx81"}]}