{"name": "Test to validate when user enters incorrect password during self verification", "status": "passed", "description": "This testcase validate error message when user enters incorrect password during self verification", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03', 'facility.admin.03']"}], "start": 1733762170205, "stop": 1733762186735, "uuid": "3524be23-0571-4084-998a-ebfc7b927c33", "historyId": "3c96bafdfce1339ec82a5b88e28fcf52", "testCaseId": "0681349741dba5374a234f8dfc1e0f11", "fullName": "tests.scenarios.job.test_parameter_verification.TestParameterVerification#test_validate_incorrect_password_self_verification", "labels": [{"name": "tag", "value": "validate_incorrect_password_self_verification"}, {"name": "tag", "value": "parameter_verification"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_parameter_verification"}, {"name": "subSuite", "value": "TestParameterVerification"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_parameter_verification"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cug1x1q", "name": "https://app.clickup.com/t/86cug1x1q"}]}