{"name": "Test to validate error when Next Task is Executed Before Task with 'Stop' action", "status": "passed", "description": "This testcase tests that user gets error when next task is executed before task with 'Stop' action", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733499096446, "stop": 1733499107413, "uuid": "851dda5d-056d-4d66-aa51-a4dd7fc1799b", "historyId": "ff900ab0dfb07f49a814a2e8ce6e4933", "testCaseId": "c70c76b179bd8109ae34124e5c76773d", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_error_when_next_task_is_executed_before_task_with_Stop_action", "labels": [{"name": "tag", "value": "error_when_next_task_is_executed_before_task_with_Stop_action"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cukrq54", "name": "https://app.clickup.com/t/86cukrq54"}]}