{"name": "Test to validate when user enters incorrect password during self verification", "status": "passed", "description": "This testcase validate error message when user enters incorrect password during self verification", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733762186737, "stop": 1733762204482, "uuid": "aaf9858c-7dc3-4b15-94f8-1d462ad69bdf", "historyId": "0e0fa64038c8e56474c8f9ffc3b13724", "testCaseId": "0681349741dba5374a234f8dfc1e0f11", "fullName": "tests.scenarios.job.test_parameter_verification.TestParameterVerification#test_validate_incorrect_password_self_verification", "labels": [{"name": "tag", "value": "validate_incorrect_password_self_verification"}, {"name": "tag", "value": "parameter_verification"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_parameter_verification"}, {"name": "subSuite", "value": "TestParameterVerification"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_parameter_verification"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cug1x1q", "name": "https://app.clickup.com/t/86cug1x1q"}]}