{"name": "Test to verify enabling peer verification on self-verification enabled parameters and vice versa", "status": "failed", "statusDetails": {"message": "AssertionError: Incorrect Password for Username: facility.admin.03 and Password: $unDay123", "trace": "self = <test_prototype_and_parameter.TestPrototypeAndParameter object at 0x79c71f57ffe0>\n\n    @allure.title(\"Test to verify enabling peer verification on self-verification enabled parameters and vice versa\")\n    @allure.description(\n        \"This test case test enabling peer verification or self verification on parameters for which one of the \"\n        \"verification is already enabled  \")\n    @allure.link(\"https://app.clickup.com/t/85zttkem5\")\n    @pytest.mark.scenario\n    @pytest.mark.create_prototype\n    @pytest.mark.enabling_verification_on_parameters_with_one_verification_type_already_enabled\n    def test_enabling_verification_on_parameters_with_one_verification_type_already_enabled(self):\n>       login(Env.get_env_data(\"QA_ADMIN_USERNAME_01\"), Env.get_env_data(\"QA_ADMIN_PASSWORD_01\"))\n\ntests/scenarios/test_prototype_and_parameter.py:780: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/unit/login_logout/login_logout.py:21: in login\n    status_200(response, \"Incorrect Password for Username: \" + user_name + \" and Password: \" + password)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = 'Incorrect Password for Username: facility.admin.03 and Password: $unDay123'\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError: Incorrect Password for Username: facility.admin.03 and Password: $unDay123\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case test enabling peer verification or self verification on parameters for which one of the verification is already enabled  ", "start": 1733749401056, "stop": 1733749431152, "uuid": "b569c1ad-f1de-451f-9a2a-c853e7a964c5", "historyId": "b31cf11f2e389c1ba34bd33397854d0a", "testCaseId": "77072c791cf6048e76a8a74b61704051", "fullName": "tests.scenarios.test_prototype_and_parameter.TestPrototypeAndParameter#test_enabling_verification_on_parameters_with_one_verification_type_already_enabled", "labels": [{"name": "tag", "value": "enabling_verification_on_parameters_with_one_verification_type_already_enabled"}, {"name": "tag", "value": "create_prototype"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios"}, {"name": "suite", "value": "test_prototype_and_parameter"}, {"name": "subSuite", "value": "TestPrototypeAndParameter"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "49291-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.test_prototype_and_parameter"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/85zttkem5", "name": "https://app.clickup.com/t/85zttkem5"}]}