{"name": "Test to validate that user get error when user tries to start the task having task executor lock enabled before completing the can not be executor task", "status": "passed", "description": "This test case tests the error when user tries to start the task having task executor lock enabled before completing the can not be executor task", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03', 'process.publisher.04']"}], "start": 1733504844217, "stop": 1733504856483, "uuid": "75503432-55d9-4148-b903-a68cc034d6f3", "historyId": "64fb232d781aa42d440ac361787f4cd6", "testCaseId": "de3fb41c1629ce59b8522d2a66eb2a40", "fullName": "tests.scenarios.job.test_task_executor_lock_execution.TestTaskExecutorLockExecution#test_start_task_before_completing_cannot_be_executor_task", "labels": [{"name": "tag", "value": "start_task_before_completing_cannot_be_executor_task"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_task_executor_lock_execution"}, {"name": "subSuite", "value": "TestTaskExecutorLockExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_task_executor_lock_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cv4ja09", "name": "https://app.clickup.com/t/86cv4ja09"}]}