{"name": "Test to validate the error when cannot be executor of task-user tries to start the task having task executor lock enabled", "status": "passed", "description": "This test case tests the error when cannot be executor of task-user tries to start the task having task executor lock enabled", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733504801192, "stop": 1733504810721, "uuid": "e18366f2-288f-48bb-876c-c425104c7f7d", "historyId": "a6b1aec4d7fee23867dc0b863f6bb07d", "testCaseId": "d5a4a48f867a005a05ca39c66e4f29d5", "fullName": "tests.scenarios.job.test_task_executor_lock_execution.TestTaskExecutorLockExecution#test_start_task_by_cannot_be_executor_of_task_user", "labels": [{"name": "tag", "value": "start_task_by_cannot_be_executor_of_task_user"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_task_executor_lock_execution"}, {"name": "subSuite", "value": "TestTaskExecutorLockExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_task_executor_lock_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cv3brzz", "name": "https://app.clickup.com/t/86cv3brzz"}]}