{"name": "This test case is to verify that user cannot create relations with existing relation name", "status": "passed", "description": "This test case is to verify that user cannot create relations with existing relation name for the object type in ontology", "start": 1733505278546, "stop": 1733505280594, "uuid": "9ae4dd87-be7b-4b50-99cd-a29e34d7373b", "historyId": "e2588fdf365d8851679f74a5496d423d", "testCaseId": "7f0c9ca72e9e8e3590938d0687bd213d", "fullName": "tests.scenarios.ontology.test_object_types_relations#test_validate_object_type_relation_name", "labels": [{"name": "tag", "value": "validate_object_type_relation_name"}, {"name": "tag", "value": "ontology"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.ontology"}, {"name": "suite", "value": "test_object_types_relations"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.ontology.test_object_types_relations"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/85ztqavmh", "name": "https://app.clickup.com/t/85ztqavmh"}]}