{"name": "Test to validate error when user tries to complete the task with executing some of the parameters", "status": "passed", "description": "This test case tests validating error when user tries to complete task after executing some of the parameters", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733498520778, "stop": 1733498545188, "uuid": "676b3718-c652-462d-8ff4-66093e77be5f", "historyId": "b16c71eb8529dc762e2b6a58e9792a17", "testCaseId": "1c767ceb1ff0f839d3f8d55eec3bf9b4", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_validate_error_on_completing_task_after_executing_parameters", "labels": [{"name": "tag", "value": "validate_error_on_completing_task_after_executing_parameters"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cu3nx81", "name": "https://app.clickup.com/t/86cu3nx81"}]}