{"name": "Test to complete the repeated task with exception", "status": "passed", "description": "This test case verify that if user can complete the repeated task with exception", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733501422925, "stop": 1733501435801, "uuid": "5c097108-556a-4c59-b6ff-325068bc6dc7", "historyId": "b117f27fb986e588be3851fb8472c0d6", "testCaseId": "c0178fa5a783ae844265f34c1d131a82", "fullName": "tests.scenarios.job.test_repeat_task.TestRepeatTask#test_complete_repeat_task_with_exception", "labels": [{"name": "tag", "value": "complete_repeat_task_with_exception"}, {"name": "tag", "value": "repeat_task"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_repeat_task"}, {"name": "subSuite", "value": "TestRepeatTask"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_repeat_task"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvw0xm0", "name": "https://app.clickup.com/t/86cvw0xm0"}]}