{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with all allowed property and task start trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with all allowed property and task start trigger", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733497728216, "stop": 1733497752512, "uuid": "b9ac3aec-5082-4d84-b81d-78683b1fbeec", "historyId": "22b850813d36f0120b3eebdc2b61a0a9", "testCaseId": "652f612a77abb942519056d0ffe896b9", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_all_allowed_property_and_task_start_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_all_allowed_property_and_task_start_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86curqagy", "name": "https://app.clickup.com/t/86curqagy"}]}