{"name": "Test to verify that user can complete job for process having resource type validation with halt parameter exception workflow enabled", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_resource_parameter_exception_management_execution.TestResourceParameterExceptionManagementExecution object at 0x7af822092300>\nuser_group_creation = 'Auto_Test_user_group_TestResourceParameterExceptionManagementExecution_1836', job_execution_by = 'user', users_list = ['process.publisher.03', 'process.publisher.04']\n\n    @allure.title(\n        \"Test to verify that user can complete job for process having resource type validation with halt parameter \"\n        \"exception workflow enabled\")\n    @allure.description(\n        \"This test case validates that user can complete job for process having resource type validation with halt \"\n        \"parameter exception workflow enabled\")\n    @allure.link(\"https://app.clickup.com/t/86cvznxgk\")\n    @pytest.mark.scenario\n    @pytest.mark.job\n    @pytest.mark.exception_management_workflow\n    @pytest.mark.validate_job_completion_on_resource_type_validation_with_halt_parameter_exception_workflow\n    @pytest.mark.parametrize(\"job_execution_by, users_list\", [\n        (\"user\", [Env.get_env_data(\"QA_PUBLISHER_USERNAME_01\"), Env.get_env_data(\"QA_PUBLISHER_USERNAME_02\")])])\n    def test_validate_job_completion_on_resource_type_validation_with_halt_parameter_exception_workflow(self,\n                                                                                                        user_group_creation,\n                                                                                                        job_execution_by,\n                                                                                                        users_list):\n>       process_data = self.process_obj.test_add_number_parameter_with_resource_type_validation_halt_parameter_exception_workflow()\n\ntests/scenarios/job/test_resource_parameter_exception_management_execution.py:313: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/scenarios/test_number_parameter_exception_management.py:55: in test_add_number_parameter_with_resource_type_validation_halt_parameter_exception_workflow\n    validate_checklist()\ntests/unit/prototyping/process.py:186: in validate_checklist\n    status_200(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = ''\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case validates that user can complete job for process having resource type validation with halt parameter exception workflow enabled", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03', 'process.publisher.04']"}], "start": 1733501672401, "stop": 1733501679349, "uuid": "d2ac97b4-519b-40f5-89ab-a1376a9ea649", "historyId": "7c95c71d7eb4f55e40312ce357c82d0a", "testCaseId": "3ce890b1c097a43b0e67038546768284", "fullName": "tests.scenarios.job.test_resource_parameter_exception_management_execution.TestResourceParameterExceptionManagementExecution#test_validate_job_completion_on_resource_type_validation_with_halt_parameter_exception_workflow", "labels": [{"name": "tag", "value": "validate_job_completion_on_resource_type_validation_with_halt_parameter_exception_workflow"}, {"name": "tag", "value": "exception_management_workflow"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_resource_parameter_exception_management_execution"}, {"name": "subSuite", "value": "TestResourceParameterExceptionManagementExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_resource_parameter_exception_management_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvznxgk", "name": "https://app.clickup.com/t/86cvznxgk"}]}