{"name": "Test to repeat task when subsequent task is started", "status": "passed", "description": "This test case validates error when user tries to repeat task without completing subsequentstarted task", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733501510594, "stop": 1733501522509, "uuid": "391fd18b-ec49-4cda-a916-edf93137606d", "historyId": "8f2139e621b7e59df219451bfc905d04", "testCaseId": "9b20e3a03711f1551e5527b260b01d9a", "fullName": "tests.scenarios.job.test_repeat_task.TestRepeatTask#test_error_repeating_task_with_starting_subsequent_task", "labels": [{"name": "tag", "value": "error_repeating_task_with_starting_subsequent_task"}, {"name": "tag", "value": "repeat_task"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_repeat_task"}, {"name": "subSuite", "value": "TestRepeatTask"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_repeat_task"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvw0ypb", "name": "https://app.clickup.com/t/86cvw0ypb"}]}